export const DELETE_STAFF_REQ_REQUEST = 'DELETE_STAFF_REQ_REQUEST'
export const DELETE_STAFF_REQ_SUCCESS = 'DELETE_STAFF_REQ_SUCCESS'
export const DELETE_STAFF_REQ_FAILURE = 'DELETE_STAFF_REQ_FAILURE'