export const GET_SPECIALIZATION_REQUEST = 'GET_SPECIALIZATION_REQUEST'
export const GET_SPECIALIZATION_SUCCESS = 'GET_SPECIALIZATION_SUCCESS'
export const GET_SPECIALIZATION_FAILURE = 'GET_SPECIALIZATION_FAILURE'