export const GET_RESOURCE_TYPES_REQUEST = 'GET_RESOURCE_TYPES_REQUEST'
export const GET_RESOURCE_TYPES_SUCCESS = 'GET_RESOURCE_TYPES_SUCCESS'
export const GET_RESOURCE_TYPES_FAILURE = 'GET_RESOURCE_TYPES_FAILURE'