export const UPDATE_BATCH_REQUEST = 'UPDATE_BATCH_REQUEST'
export const UPDATE_BATCH_SUCCESS = 'UPDATE_BATCH_SUCCESS'
export const UPDATE_BATCH_FAILURE = 'UPDATE_BATCH_FAILURE'
export const RESET_STATE = 'RESET_STATE'