export const GET_INSTITUTE_TYPE_REQUEST = 'GET_INSTITUTE_TYPE_REQUEST'
export const GET_INSTITUTE_TYPE_SUCCESS = 'GET_INSTITUTE_TYPE_SUCCESS'
export const GET_INSTITUTE_TYPE_FAILURE = 'GET_INSTITUTE_TYPE_FAILURE'