export const ADD_OFFER_COURSE_REQUEST = 'ADD_OFFER_COURSE_REQUEST'
export const ADD_OFFER_COURSE_SUCCESS = 'ADD_OFFER_COURSE_SUCCESS'
export const ADD_OFFER_COURSE_FAILURE = 'ADD_OFFER_COURSE_FAILURE'