export const UPDATE_OFFERED_COURSE_REQUEST = 'UPDATE_OFFERED_COURSE_REQUEST'
export const UPDATE_OFFERED_COURSE_SUCCESS = 'UPDATE_OFFERED_COURSE_SUCCESS'
export const UPDATE_OFFERED_COURSE_FAILURE = 'UPDATE_OFFERED_COURSE_FAILURE'
export const RESET_STATE = 'RESET_STATE'