export const UPDATE_FACULTY_REQUEST = 'UPDATE_FACULTY_REQUEST'
export const UPDATE_FACULTY_SUCCESS = 'UPDATE_FACULTY_SUCCESS'
export const UPDATE_FACULTY_FAILURE = 'UPDATE_FACULTY_FAILURE'
export const RESET_STATE = 'RESET_STATE'