export const ASSIGN_COURSE_REQUEST = 'ASSIGN_COURSE_REQUEST'
export const ASSIGN_COURSE_SUCCESS = 'ASSIGN_COURSE_SUCCESS'
export const ASSIGN_COURSE_FAILURE = 'ASSIGN_COURSE_FAILURE'
export const RESET_STATE = 'RESET_STATE'