export const UPDATE_ROOM_REQUEST = 'UPDATE_ROOM_REQUEST'
export const UPDATE_ROOM_SUCCESS = 'UPDATE_ROOM_SUCCESS'
export const UPDATE_ROOM_FAILURE = 'UPDATE_ROOM_FAILURE'
export const RESET_STATE = 'RESET_STATE'