export const GET_OFFERED_COURSES_REQUEST = 'GET_OFFERED_COURSES_REQUEST'
export const GET_OFFERED_COURSES_SUCCESS = 'GET_OFFERED_COURSES_SUCCESS'
export const GET_OFFERED_COURSES_FAILURE = 'GET_OFFERED_COURSES_FAILURE'