export const ADD_ALLOCATE_FACULTY_REQUEST = 'ADD_ALLOCATE_FACULTY_REQUEST'
export const ADD_ALLOCATE_FACULTY_SUCCESS = 'ADD_ALLOCATE_FACULTY_SUCCESS'
export const ADD_ALLOCATE_FACULTY_FAILURE = 'ADD_ALLOCATE_FACULTY_FAILURE'
export const RESET_STATE = 'RESET_STATE'