export const ASSIGNED_COURSES_REQUEST = 'ASSIGNED_COURSES_REQUEST'
export const ASSIGNED_COURSES_SUCCESS = 'ASSIGNED_COURSES_SUCCESS'
export const ASSIGNED_COURSES_FAILURE = 'ASSIGNED_COURSES_FAILURE'