export const DELETE_ALLOCATED_FACULTY_REQUEST = 'DELETE_ALLOCATED_FACULTY_REQUEST'
export const DELETE_ALLOCATED_FACULTY_SUCCESS = 'DELETE_ALLOCATED_FACULTY_SUCCESS'
export const DELETE_ALLOCATED_FACULTY_FAILURE = 'DELETE_ALLOCATED_FACULTY_FAILURE'
export const RESET_STATE = 'RESET_STATE'