export const ADD_SPECIALIZATION_REQUEST = 'ADD_SPECIALIZATION_REQUEST'
export const ADD_SPECIALIZATION_SUCCESS = 'ADD_SPECIALIZATION_SUCCESS'
export const ADD_SPECIALIZATION_FAILURE = 'ADD_SPECIALIZATION_FAILURE'
export const RESET_STATE = 'RESET_STATE'