export const GET_OBJS_PER_RES_REQUEST = 'GET_OBJS_PER_RES_REQUEST'
export const GET_OBJS_PER_RES_SUCCESS = 'GET_OBJS_PER_RES_SUCCESS'
export const GET_OBJS_PER_RES_FAILURE = 'GET_OBJS_PER_RES_FAILURE'