export const UPDATE_POSITION_REQUEST = 'UPDATE_POSITION_REQUEST'
export const UPDATE_POSITION_SUCCESS = 'UPDATE_POSITION_SUCCESS'
export const UPDATE_POSITION_FAILURE = 'UPDATE_POSITION_FAILURE'
export const RESET_STATE = 'RESET_STATE'