export const UPDATE_ALLOCATED_FACULTY_REQUEST = 'UPDATE_ALLOCATED_FACULTY_REQUEST'
export const UPDATE_ALLOCATED_FACULTY_SUCCESS = 'UPDATE_ALLOCATED_FACULTY_SUCCESS'
export const UPDATE_ALLOCATED_FACULTY_FAILURE = 'UPDATE_ALLOCATED_FACULTY_FAILURE'
export const RESET_STATE = 'RESET_STATE'