export const UPDATE_INSTITUTE_REQUEST = 'UPDATE_INSTITUTE_REQUEST'
export const UPDATE_INSTITUTE_SUCCESS = 'UPDATE_INSTITUTE_SUCCESS'
export const UPDATE_INSTITUTE_FAILURE = 'UPDATE_INSTITUTE_FAILURE'