export const UPDATE_WEIGHTAGE_REQUEST = 'UPDATE_WEIGHTAGE_REQUEST'
export const UPDATE_WEIGHTAGE_SUCCESS = 'UPDATE_WEIGHTAGE_SUCCESS'
export const UPDATE_WEIGHTAGE_FAILURE = 'UPDATE_WEIGHTAGE_FAILURE'